#!/bin/bash

# Array of topics
topics=(
    "Hello World"
    "Values"
    "Variables"
    "Constants"
    "For"
    "If/Else"
    "Switch"
    "Arrays"
    "Slices"
    "Maps"
    "Functions"
    "Multiple Return Values"
    "Variadic Functions"
    "Closures"
    "Recursion"
    "Range over Built-in Types"
    "Pointers"
    "Strings and Runes"
    "Structs"
    "Methods"
    "Interfaces"
    "Enums"
    "Struct Embedding"
    "Generics"
    "Range over Iterators"
    "Errors"
    "Custom Errors"
    "Goroutines"
    "Channels"
    "Channel Buffering"
    "Channel Synchronization"
    "Channel Directions"
    "Select"
    "Timeouts"
    "Non-Blocking Channel Operations"
    "Closing Channels"
    "Range over Channels"
    "Timers"
    "Tickers"
    "Worker Pools"
    "WaitGroups"
    "Rate Limiting"
    "Atomic Counters"
    "Mutexes"
    "Stateful Goroutines"
    "Sorting"
    "Sorting by Functions"
    "Panic"
    "Defer"
    "Recover"
    "String Functions"
    "String Formatting"
    "Text Templates"
    "Regular Expressions"
    "JSON"
    "XML"
    "Time"
    "Epoch"
    "Time Formatting / Parsing"
    "Random Numbers"
    "Number Parsing"
    "URL Parsing"
    "SHA256 Hashes"
    "Base64 Encoding"
    "Reading Files"
    "Writing Files"
    "Line Filters"
    "File Paths"
    "Directories"
    "Temporary Files and Directories"
    "Embed Directive"
    "Testing and Benchmarking"
    "Command-Line Arguments"
    "Command-Line Flags"
    "Command-Line Subcommands"
    "Environment Variables"
    "Logging"
    "HTTP Client"
    "HTTP Server"
    "Context"
    "Spawning Processes"
    "Exec'ing Processes"
    "Signals"
    "Exit"
)

# Iterate over the topics array
for topic in "${topics[@]}"; do
    # Replace spaces with hyphens and convert to lowercase
    filename=$(echo "$topic" | tr ' ' '-' | tr '[:upper:]' '[:lower:]').go
    
    # Create the .go file and add the package main declaration
    echo "package main" > "$filename"
done